#!/usr/bin/env python3
import subprocess


@click.command()
@click.option('-d', '--directory', default=Path.cwd())
def run(directory):
  subprocess.run('parallel convert "{} {.}.pdf" ::: *.jpg')


if __name__ == '__main__':
  run()
